### ISSUE TITLE
Why are executed only 4 tests instead of 6?

### ISSUE THREAD

**Issue by scholzj** [Eurex-Clearing-Messaging-Interfaces/C-Code-Examples#4]
The code should contain 6 tests:
- 2x Proton
- 2x Qpid Messaging with AMQP 0-10
- 2x Qpid Messaging with AMQP 1.0

But it looks like only 4 tests are executed:

```
Test project /home/ubuntu/C-Code-Examples/build
    Start 1: Broadcaster_test
1/4 Test #1: Broadcaster_test .................   Passed   20.34 sec
    Start 2: Responder_test
2/4 Test #2: Responder_test ...................   Passed    0.18 sec
    Start 3: Broadcaster_test
3/4 Test #3: Broadcaster_test .................   Passed    0.02 sec
    Start 4: Responder_test
4/4 Test #4: Responder_test ...................   Passed    0.02 sec

100% tests passed, 0 tests failed out of 4
```

**Comment by tomas-soltys** [comment]
Tests are written using boost library where each test may contain several testcases. Here tests no. 1 and no. 2 both consist of two test cases for AMQP 0.10 and AMQP 1.0.
Maybe some better form of output is needed.

**Comment by scholzj** [comment]
Ok. In that case this issue can be closed.
